name = "All The Trains MTR"
author = "igaktbr"
version = "5.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8630d4aa99d4955922baa0399387f6d218fd41827956e559a5aa6d87219ccfba"

[versions]
fabric = "0.19.5"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.19.2", "1.19.4", "1.20", "1.20.1"]
