name = "All The Trains MTR"
author = "igaktbr"
version = "5.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f37210380dcb5516cbdf6f16ed66f444b244e18253e34b18ad110fd30f42dbdf"

[versions]
fabric = "0.19.5"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.19.2", "1.19.4", "1.20", "1.20.1"]
