name = "All The Trains MTR"
author = "igaktbr"
version = "4.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4800b44e41d249257952bf5a2bd76d78e44e61a768018b28eaa287487dbe9ce3"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.19.2", "1.19.4", "1.20", "1.20.1"]
